### ISSUE TITLE
Docker erlang-alpine image

### ISSUE THREAD

**Issue by joaohf** [SpaceTime-IoT/presence-sample#1]
Hi,

Where did you get the ' tsloughter/erlang-alpine:20.0.1' ? I would like to see the Dockerfile. I think that I have the same issue as https://github.com/c0b/docker-erlang-otp/issues/57

https://github.com/SpaceTime-IoT/presence-sample/blob/master/Dockerfile#L1

**Comment by tsloughter** [comment]
Yes and no :). Here is the dockerfile https://github.com/tsloughter/docker-erlang-otp/blob/rebar3-gcloud/20/alpine/Dockerfile

I thought the official Alpine image would work now, it no longer leaves out most of the Erlang libs. So I was just now trying to update the dockerfile in this repo to use it instead but it is failing because it can't find erl interface... `cannot find -lei`, so may be some more changed needed in the official image, at least for projects with C code.

**Comment by joaohf** [comment]
Ok, thank you. I got the same issue about -lei using the erlang official Alpine image.

**Comment by tsloughter** [comment]
Ah, please give a +1 to my patch to fix that then :) https://github.com/c0b/docker-erlang-otp/pull/78
